# Generated by Django 3.1.13 on 2022-01-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='answers',
            field=models.JSONField(),
        ),
    ]
