# Generated by Django 3.1.13 on 2022-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0002_auto_20220104_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DONE', 'Done'), ('CANCEL', 'Cancel'), ('DEACTIVATE', 'Deactivate')], default='ACTIVE', max_length=35),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DONE', 'Done'), ('CANCEL', 'Cancel'), ('DEACTIVATE', 'Deactivate')], default='ACTIVE', max_length=35),
        ),
    ]
