# Generated by Django 3.1.13 on 2022-01-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0003_auto_20220104_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='disabled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
